apiVersion: velero.io/v1
kind: Backup
metadata:
  name: mysql-backup01
  namespace: openshift-adp
  labels:
    velero.io/storage-location: dpa1-1
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: true
  includedNamespaces:
    - a-exampleapp
  itemOperationTimeout: 4h0m0s
  snapshotMoveData: false
  storageLocation: dpa1-1
  ttl: 720h0m0s