apiVersion: velero.io/v1
kind: Restore
metadata:
  namespace: openshift-adp
  name: restore-wordpress-2
spec:
  backupName: wordpress-backup
  restorePVs: true
  includedNamespaces:
  - a2-wordpress
  namespaceMapping:
    a2-wordpress: a-exampleapp-restore
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io